counting = {
    "One": "Satu",
    "Two": "Dua",
    "Three": "Tiga",
    "Four": "Empat",
    "Five": "Lima",
    "Six": "Enam",
    "Seven": "Tujuh",
    "Eight": "Delapan",
    "Nine": "Sembilan",
    "Ten": "Sepuluh",
    "Eleven": "Sebelas",
    "Twelve": "Dua belas",
    "Thirteen": "Tiga belas",
    "Fourteen": "Empat belas",
    "Fifteen": "Lima belas",
    "Sixteen": "Enam belas",
    "Seventeen": "Tujuh belas",
    "Eighteen": "Delapan belas",
    "Nineteen": "Sembilan belas",
    "Twenty": "Dua puluh",
    "Twenty-one": "Dua puluh satu",
    "Twenty-two": "Dua puluh dua",
    "Twenty-three": "Dua puluh tiga",
    "Twenty-four": "Dua puluh empat",
    "Twenty-five": "Dua puluh lima",
    "Twenty-six": "Dua puluh enam",
    "Twenty-seven": "Dua puluh tujuh",
    "Twenty-eight": "Dua puluh delapan",
    "Twenty-nine": "Dua puluh sembilan",
    "Thirty": "Tiga puluh",
    "Thirty-one": "Tiga puluh satu",
    "Thirty-two": "Tiga puluh dua",
    "Thirty-three": "Tiga puluh tiga",
    "Thirty-four": "Tiga puluh empat",
    "Thirty-five": "Tiga puluh lima",
    "Thirty-six": "Tiga puluh enam",
    "Thirty-seven": "Tiga puluh tujuh",
    "Thirty-eight": "Tiga puluh delapan",
    "Thirty-nine": "Tiga puluh sembilan",
    "Forty": "Empat puluh",
    "Forty-one": "Empat puluh satu",
    "Forty-two": "Empat puluh dua",
    "Forty-three": "Empat puluh tiga",
    "Forty-four": "Empat puluh empat",
    "Forty-five": "Empat puluh lima",
    "Forty-six": "Empat puluh enam",
    "Forty-seven": "Empat puluh tujuh",
    "Forty-eight": "Empat puluh delapan",
    "Forty-nine": "Empat puluh sembilan",
    "Fifty": "Lima puluh",
    "Fifty-one": "Lima puluh satu",
    "Fifty-two": "Lima puluh dua",
    "Fifty-three": "Lima puluh tiga",
    "Fifty-four": "Lima puluh empat",
    "Fifty-five": "Lima puluh lima",
    "Fifty-six": "Lima puluh enam",
    "Fifty-seven": "Lima puluh tujuh",
    "Fifty-eight": "Lima puluh delapan",
    "Fifty-nine": "Lima puluh sembilan",
    "Sixty": "Enam puluh",
    "Sixty-one": "Enam puluh satu",
    "Sixty-two": "Enam puluh dua",
    "Sixty-three": "Enam puluh tiga",
    "Sixty-four": "Enam puluh empat",
    "Sixty-five": "Enam puluh lima",
    "Sixty-six": "Enam puluh enam",
    "Sixty-seven": "Enam puluh tujuh",
    "Sixty-eight": "Enam puluh delapan",
    "Sixty-nine": "Enam puluh sembilan",
    "Seventy": "Tujuh puluh",
    "Seventy-one": "Tujuh puluh satu",
    "Seventy-two": "Tujuh puluh dua",
    "Seventy-three": "Tujuh puluh tiga",
    "Seventy-four": "Tujuh puluh empat",
    "Seventy-five": "Tujuh puluh lima",
    "Seventy-six": "Tujuh puluh enam",
    "Seventy-seven": "Tujuh puluh tujuh",
    "Seventy-eight": "Tujuh puluh delapan",
    "Seventy-nine": "Tujuh puluh sembilan",
    "Eighty": "Delapan puluh",
    "Eighty-one": "Delapan puluh satu",
    "Eighty-two": "Delapan puluh dua",
    "Eighty-three": "Delapan puluh tiga",
    "Eighty-four": "Delapan puluh empat",
    "Eighty-five": "Delapan puluh lima",
    "Eighty-six": "Delapan puluh enam",
    "Eighty-seven": "Delapan puluh tujuh",
    "Eighty-eight": "Delapan puluh delapan",
    "Eighty-nine": "Delapan puluh sembilan",
    "Ninety": "Sembilan puluh",
    "Ninety-one": "Sembilan puluh satu",
    "Ninety-two": "Sembilan puluh dua",
    "Ninety-three": "Sembilan puluh tiga",
    "Ninety-four": "Sembilan puluh empat",
    "Ninety-five": "Sembilan puluh lima",
    "Ninety-six": "Sembilan puluh enam",
    "Ninety-seven": "Sembilan puluh tujuh",
    "Ninety-eight": "Sembilan puluh delapan",
    "Ninety-nine": "Sembilan puluh sembilan",
    "One hundred": "Seratus"
}
