phrases = {
    "Good morning": "Selamat pagi",
    "Good afternoon": "Selamat siang",
    "Good evening": "Selamat sore",
    "Good night": "Selamat malam",
    "Goodbye": "Selamat tinggal",
    "How are you?": "Apa kabar?",
    "I am fine": "Saya baik-baik saja",
    "What is your name?": "Siapa nama Anda?",
    "My name is...": "Nama saya...",
    "Where are you from?": "Dari mana Anda?",
    "I am from...": "Saya dari...",
    "Do you speak English?": "Apakah Anda berbicara bahasa Inggris?",
    "I don't understand": "Saya tidak mengerti",
    "How much is this?": "Berapa harganya ini?",
    "I love you": "Aku cinta kamu",
    "Have a nice day": "Semoga hari menyenangkan",
    "Can you help me?": "Bisakah kamu membantu saya?",
    "What's your name?": "Siapa nama kamu?",
    "Where is the bathroom?": "Dimana kamar mandi?",
    "See you later": "Sampai jumpa nanti",
    "Can you repeat that, please?": "Bisa diulang, tolong?",
    "How can I help you?": "Bagaimana saya bisa membantumu?",
    "I am hungry": "Saya lapar",
    "I am thirsty": "Saya haus",
    "What time is it?": "Jam berapa?",
    "Do you see that guy over there?": "Apakah Anda melihat orang itu di sana?",
    "I'll tell you later": "Saya akan memberitahu Anda nanti",
    "Do you have any questions?": "Apakah Anda punya pertanyaan?",
    "Can I have the bill, please?": "Bisa minta tagihannya, tolong?",
    "Where is the nearest hospital?": "Dimana rumah sakit terdekat?",
    "I need a doctor": "Saya butuh dokter",
    "I am lost": "Saya tersesat",
    "Can you show me the way?": "Bisakah Anda menunjukkan jalannya?",
    "How do I get to the airport?": "Bagaimana cara menuju ke bandara?",
    "Is this seat taken?": "Apakah kursi ini sudah ada yang duduki?",
    "Can I have a glass of water?": "Bisa minta segelas air?",
    "Where can I find a taxi?": "Dimana saya bisa menemukan taksi?",
    "What is the time difference?": "Berapa perbedaan waktunya?",
    "Can you speak more slowly?": "Bisakah Anda berbicara lebih lambat?",
    "Can you write it down?": "Bisakah Anda menuliskannya?",
    "How far is it?": "Seberapa jauh itu?",
    "What is your phone number?": "Berapa nomor telepon Anda?",
    "Can I call you?": "Bolehkah saya menelepon Anda?",
    "Where can I exchange money?": "Dimana saya bisa menukar uang?",
    "Do you accept credit cards?": "Apakah Anda menerima kartu kredit?",
    "Is there a pharmacy nearby?": "Apakah ada apotek di dekat sini?",
    "Where is the nearest police station?": "Dimana kantor polisi terdekat?",
    "I need help": "Saya butuh bantuan",
    "Is it safe here?": "Apakah aman di sini?",
    "I am a tourist": "Saya seorang turis",
    "I am here on business": "Saya di sini untuk urusan bisnis",
    "I am here on vacation": "Saya di sini untuk liburan"
}
